### ISSUE TITLE
Lazy loading conflicts

### ISSUE THREAD

**Issue by eric-hansen** [hackorum/VapourNvim#10]
After merging in 7c0a4993ed97ebb45cbad4ec3da048f28c861c28 I'm experiencing a lot of treesitter errors on start up.  After resolving that (by removing the `cmd` bit from the plugins init file) I get an error about compe.  

So I'm making some changes to my PR for #5 but also wanted to open this in case there's more to it.  

I don't really understand how lazy loading works for Packer.

**Comment by eric-hansen** [comment]
I figured out what the issue was, sort of.  I'm able to resolve it, but can't explain in-depth the why.  I'll fix this in my PR for #5 

It seems when lazy-loading, if there's any configuration to it, it should be passed in as a config to Packer:

```lua
-- lua/vapour/plugins/init.lua
use {'hrsh7th/nvim-compe', event = {"InsertEnter"}, config = function() require'compe-config' end}

-- lua/compe-config/init.lua
<snipped>

return {
  enabled = true;
  autocomplete = true;
  debug = false;
  min_length = 1;
  preselect = 'enable';
  throttle_time = 80;
  source_timeout = 200;
  incomplete_delay = 400;
  max_abbr_width = 100;
  max_kind_width = 100;
  max_menu_width = 100;
  documentation = true;

  source = {
    path = true;
    buffer = true;
    calc = true;
    vsnip = true;
    nvim_lsp = true;
    nvim_lua = true;
    spell = true;
    tags = true;
    snippets_nvim = true;
    treesitter = true;
  };
}
```

So I'll need to make this change to all of the lazy-loaded packages where this is happening.

**Comment by eric-hansen** [comment]
The issue here is when a package is lazy-loaded, `vim.cmd [[packadd ...]]` needs to be used prior to `require()`.  So what I may need to do is add `vim.cmd [[ <pkg> ]]` to `Vapour.utils.plugins.require_if_installed()` or something, because otherwise it'll just keep causing issues.

**Comment by hackorum** [comment]
I think e67d293 fixes this for now. Maybe we can add a lazy load parameter to require_if_installed and if it is true then do vim.cmd('packadd ' .. pkg) or something like that?

**Comment by hackorum** [comment]
I have implemented the checking for lazy loading in the require_if_installed function and tested it with the markdown-preview.nvim plugin and it seems to be working fine.

**Comment by eric-hansen** [comment]
I've tweaked the `require_if_installed` function slightly since I started realizing not all repos are the module names, which is a little annoying.  But I'll port your changes as well over.

I didn't say this yesterday as I was exhausted by the time, but I think just part of the issue is some need to not be lazy-loaded, while others do.

Locally how I have it now is `which-key` is not lazy loaded, but for example NvimTree is.  In the plugins conf it's loaded on `:NvimTreeToggle` command, so when I do `<leader>e` then it gets loaded without issue.

This might be a good safe way to go about this.  Because doing `packadd` imo defeats the purpose of lazy-loading.  I just couldn't get it to work any other way prior, but I think the above is a sane approach.

**Comment by hackorum** [comment]
Now I get "which-key" not existing every time I start neovim. I am not sure if it is good or bad. Does this mean that it is getting lazy loaded?

**Comment by eric-hansen** [comment]
> Now I get "which-key" not existing every time I start neovim. I am not sure if it is good or bad. Does this mean that it is getting lazy loaded?

Yeah.  I got that fixed in my modularize-vapour branch, the main thing I'm running into right now is auto-complete not working for some reason.  So been trying to figure that out.
