### ISSUE TITLE
Error on "nvim +PackerSync"

### ISSUE THREAD

**Issue by insidec** [hackorum/VapourNvim#18]
Error on "**nvim +PackerSync**"

Hey, I get an error when running "**nvim +PackerSync**"
**ERROR**: [packer.nvim] [ERROR 20:58:38 async.lua:20: Error in coroutine: ...ite/pack/packer/start/packer.nvim/lua/packer/compile.lua:598: attempt to index a nil value

![2021-08-14-210312_1920x1080_scrot](https://user-images.githubusercontent.com/88802434/129459940-0ae29492-42df-4b60-a56e-3df69d0c4232.png)

**Comment by hackorum** [comment]
Even I get that error when I install it fresh. Just press q and then :q. Then open any file. You will see that everything works fine. Then you can read the [wiki](https://github.com/hackorum/VapourNvim/wiki/User-Configuration) and enable a few plugins in your user-config folder.

**Comment by hackorum** [comment]
Fixed in 7a0ebab
