### ISSUE TITLE
freshly cloned repo causes lua errors in most recent nvim

### ISSUE THREAD

**Issue by bronsen** [hackorum/VapourNvim#2]
I have nvim compiled from git HEAD (version NVIM v0.5.0-dev+1425-g7da86f55a)

When I remove everything regarding my old config and clone the repo to ~/.config/nvim and then start `nvim +PackerSync` I get an error: 

```
Error detected while processing /home/bronsen/.config/nvim/init.lua:
line    1:
E5113: Error while calling lua chunk: ...onsen/.local/neovim/share/nvim/runtime/lua/vim/_meta.lua:21: attempt to index local 'i
nfo' (a nil value)
Press ENTER or type command to continue
```

`/home/bronsen/.local/neovim/share/nvim/runtime` is my $VIMRUNTIME

**Comment by hackorum** [comment]
I have fixed this. You can pull the changes.
