### ISSUE TITLE
Code action not working

### ISSUE THREAD

**Issue by barungh** [hackorum/VapourNvim#21]
Where is LSP saga related key bindings ?

I don't see them in keybindings/init.lua

![vapour1](https://user-images.githubusercontent.com/12285528/130000884-cb8f22f8-18c2-4334-91c3-8dcdd7fde099.png)
 
Although `:Lspsaga code_action` works, but `ca` doesn't work

![vapour2](https://user-images.githubusercontent.com/12285528/130001087-40b8546e-954a-4bb3-8e5a-785a0f5700a8.png)

**Comment by hackorum** [comment]
Do you have the language servers installed?

**Comment by barungh** [comment]
> Do you have the language servers installed?

Yes language servers are installed , just `ca` for **code action** is not working 
How to invoke it ? I guess just pressing `ca` in normal mode

**Comment by hackorum** [comment]
And the keybinding is defined in `lua/language-servers/init.lua` in line 92.

**Comment by barungh** [comment]
> And the keybinding is defined in `lua/language-servers/init.lua` in line 92.

Ok, thanks, lemme check them

**Comment by hackorum** [comment]
Maybe you are not typing it fast enough.

**Comment by barungh** [comment]
> Maybe you are not typing it fast enough.

pressing `c` opens different which key menu, ( may be I caused some conflicts by enabling various plugins )

I solved my problem by modifying keybinding of `Lspsaga`

Thanks for pointing me to keybinding file

![image](https://user-images.githubusercontent.com/12285528/130002516-495fc6d3-bb77-4271-9108-54ec0af9fd1d.png)
