### ISSUE TITLE
Enabling treesitter

### ISSUE THREAD

**Issue by shivahnshankar** [hackorum/VapourNvim#22]
After install, I found that treesitter was not enabled. I guessed and added: 
`Vapour.plugins.treesitter.enabled = true`
in my init.lua.

1.  I believe it should be enabled by default
2. Discoverability would be much better if there was autocomplete, so that when I type 'Vapour.plugins.' it should list all possible options
3. The tree sitter plugin was installed but I still do not have access to the TSInstall command.
Did I miss any step?

**Comment by shivahnshankar** [comment]
Hmm..I am getting "Attempt to index a null value" when I try to PackerCompile. Related maybe?

**Comment by hackorum** [comment]
> I believe it should be enabled by default

Many people use treesitter, but not everyone wants treesitter support by default. If you want it, you can enable it pretty easily.

> Discoverability would be much better if there was autocomplete, so that when I type 'Vapour.plugins.' it should list all possible options

If you want autocomplete, it is the same process. Just enable the plugin in your user-config file. You can find the `Vapour` object in `lua/vapour/init.lua`

> The tree sitter plugin was installed but I still do not have access to the TSInstall command.
Did I miss any step?

Could you please send some screenshots? It would be more helpful to find what's wrong.

I hope this helped.

**Comment by hackorum** [comment]
@shivahnshankar Did it get fixed yet?

**Comment by hackorum** [comment]
> Hmm..I am getting "Attempt to index a null value" when I try to PackerCompile. Related maybe?

It has been fixed in 7a0ebab
