### ISSUE TITLE
Error in windows

### ISSUE THREAD

**Issue by HypsterOP** [hackorum/VapourNvim#23]
Vim(packadd):E919: Directory not found in 'packpath' : 'pack/*/opt/nvim-lspconfig'

**Comment by hackorum** [comment]
Could you please share a screenshot or video of when the error occurs?

**Comment by H4ckint0sh** [comment]
![Skärmavbild 2021-09-08 kl  11 34 56](https://user-images.githubusercontent.com/44159647/132485119-f56dd868-d384-462f-9208-02c5948aa190.png)

**Comment by HypsterOP** [comment]
> 
> 
> Could you please share a screenshot or video of when the error occurs?

Yes, could you wait for a couple of minutes im finishing a school assignment.

**Comment by HypsterOP** [comment]
> 
> 
> ![Skärmavbild 2021-09-08 kl 11 34 56](https://user-images.githubusercontent.com/44159647/132485119-f56dd868-d384-462f-9208-02c5948aa190.png)

yes i have the same error

**Comment by hackorum** [comment]
What is the output of :set setrtp

**Comment by hackorum** [comment]
And does this occur every time you open nvim?

**Comment by HypsterOP** [comment]
Also i tried it _**again.**_, and when i'm trying to sync the plugins...[error](https://ibb.co/xFHySFs)

**Comment by HypsterOP** [comment]
> 
> 
> And does this occur every time you open nvim?

yes

**Comment by HypsterOP** [comment]
> 
> 
> What is the output of :set setrtp

Unknown Option: setrtp

**Comment by hackorum** [comment]
I tried on fresh installs of windows, linux and also macos but I was not able to reproduce it.

**Comment by H4ckint0sh** [comment]
I tried this on 3 machines (all mac) and the same error occurred in all 3.

**Comment by hackorum** [comment]
Does upgrade to 0.6 work?

**Comment by H4ckint0sh** [comment]
If you mean Neovim 0.6. I have altardy tried it and got the same error.

**Comment by hackorum** [comment]
It was an issue with nvim-autopairs. The after keyword was set to {'nvim-compe'} even when compe was disabled. Fixed in 7a0ebab
