### ISSUE TITLE
Error when running :PackerSync

### ISSUE THREAD

**Issue by H4ckint0sh** [hackorum/VapourNvim#24]
<img width="922" alt="Skärmavbild 2021-09-07 kl  22 39 50" src="https://user-images.githubusercontent.com/44159647/132408200-ea5fccb5-d20d-4907-b3f0-c4240fe38920.png">

**Comment by hackorum** [comment]
You can ignore that error. After you open nvim again it will work fine.

**Comment by H4ckint0sh** [comment]
Problem is it does not. I have enabled some plugins like treeview and klicking space + E does not trigger it.

**Comment by hackorum** [comment]
It was an issue with nvim-autopairs. The after keyword was set to `{'nvim-compe'}` even when compe was disabled. Fix in 7a0ebab

**Comment by H4ckint0sh** [comment]
Thnkyou, it is working now.
