### ISSUE TITLE
Toogleterm does not work!

### ISSUE THREAD

**Issue by H4ckint0sh** [hackorum/VapourNvim#25]

**Comment by hackorum** [comment]
You need to enable it in your `lua/vapour/user-config/init.lua` file by using `Vapour.plugins.toggleterm.enabled = true`. After that re-enter nvim and do `:PackerSync`. Then press ctrl+\ or space+T and t to get a bottom split, space+T and f to open floating terminal or space+T and l to open lazygit in a floating window.
You can also open the user config file using space+E

**Comment by H4ckint0sh** [comment]
Already Done that. I have enabled it and space + T + t takes me to split terminal. But no matter what i do i am not able to exit.
I have tried space + T , contol +\, try to enter normal mode, i am just able to enter commands into terminal.
The only thing working is if i click On the area saying toggleterm in bortom of the window and enter :q.
This is also case igen i enter float terminal, it only exits if i klick outside of it.

**Comment by hackorum** [comment]
You can just type exit in the terminal to exit it.

**Comment by hackorum** [comment]
If you want to get into normal mode in the terminal then put this in your user config file: `vim.api.nvim_set_keymap('t', '<esc>', '<C-\\><C-n>', {noremap = true, silent = true})
`

**Comment by H4ckint0sh** [comment]
But should not i be able to toggle it with ”space T” or something else?
Thnkyou by the way for answering my noob questions.

**Comment by hackorum** [comment]
space T will only work in terminal if you are in normal mode

**Comment by hackorum** [comment]
ctrl+\ will hide the terminal or unhide it

**Comment by hackorum** [comment]
Can I close the issue now?

**Comment by H4ckint0sh** [comment]
Yes, I will test it later.
