### ISSUE TITLE
Nothing seemed to have happened after installation

### ISSUE THREAD

**Issue by tabot-kevin** [hackorum/VapourNvim#27]
I installed as you instructed on the Readme file,  but after installation I opened nvim and it is as if nothing happened, also there is a message at the bottom saying 'You need to install treesitter'

**Comment by hackorum** [comment]
Which os are you using? Could you also post some screenshots?

**Comment by KarolusD** [comment]
@tabot-kevin go to your vapour nivm plugin settings (~/.config/nvim/lua/vapour/init.lua) and turn on treesitter. After that execute :PackerUpdate and reopen nvim, you should be fine. Keep in mind that most plugins are turn off by default.

**Comment by hackorum** [comment]
He said that the config did not work. Maybe he is using windows and he has to install it in ~/AppData/Local/nvim

**Comment by KarolusD** [comment]
Hm, maybe, but I've got the same error message: 'You need to install treesitter'. I believe this happened because of treesitter being turn off by default.

**Comment by hackorum** [comment]
Where do you get this error?

**Comment by KarolusD** [comment]
On the first nvim launch (after installation) os: BigSur

**Comment by tabot-kevin** [comment]
<img width="1920" alt="properties" src="https://user-images.githubusercontent.com/81575086/134912678-afe430e0-f65d-466a-8c34-8d7ec5c64057.png">

<img width="1405" alt="installation" src="https://user-images.githubusercontent.com/81575086/134912910-4d655645-a7b1-4c6e-b80c-522f77f9026b.png">

<img width="1788" alt="during_installation" src="https://user-images.githubusercontent.com/81575086/134912947-1e5297a0-0cb0-4249-93d5-005b5c82295b.png">

<img width="1920" alt="after_installation" src="https://user-images.githubusercontent.com/81575086/134913013-1d808429-eb47-46fb-80ea-bad5d26d9a99.png">

**Comment by hackorum** [comment]
The installation was successful. You can install some plugins by enabling them.

**Comment by KarolusD** [comment]
@tabot-kevin Also to make nvim/tree-sitter work as expected you should install and turn on some of the languages servers that you're using. 

- Language servers: https://github.com/hackorum/VapourNvim/wiki/Language-Servers

**Comment by tabot-kevin** [comment]
Where do I enable the plugins? Do I modify the `Vapour` object in`./lua/vapour/init.lua` set the enable property to true for plugins and language servers that I want?

**Comment by hackorum** [comment]
You need to enable plugins in `./lua/vapour/user-config/init.lua`. You can open the file anytime by pressing <space>E

**Comment by hackorum** [comment]
You can refer to my config:
```lua
Vapour.plugins.colorizer.enabled = true
Vapour.plugins.bufferline.enabled = true
Vapour.plugins.galaxyline.enabled = true
Vapour.plugins.dashboard.enabled = true
Vapour.plugins.toggleterm.enabled = true
Vapour.plugins.treesitter.enabled = true
Vapour.plugins.rainbow_parentheses.enabled = true
Vapour.plugins.closetag.enabled = true
Vapour.plugins.vsnip.enabled = true
Vapour.plugins.markdown_preview.enabled = true
Vapour.plugins.telescope.enabled = true
Vapour.plugins.nvim_tree.enabled = true
Vapour.plugins.dial.enabled = true
Vapour.plugins.format.enabled = true
Vapour.plugins.nvim_comment.enabled = true
Vapour.plugins.compe.enabled = true
Vapour.plugins.indent_blankline.enabled = true
-- Vapour.plugins.indent_blankline.enable_rainbow_colors = true

Vapour.language_servers.sumneko_lua.enabled = true
Vapour.language_servers.bashls.enabled = true
Vapour.language_servers.cssls.enabled = true
Vapour.language_servers.html.enabled = true
Vapour.language_servers.tsserver.enabled = true
Vapour.language_servers.pylsp.enabled = true
Vapour.language_servers.jsonls.enabled = true

Vapour.settings.colorscheme = 'tokyonight'
Vapour.plugins.which_key.user_defined.t = {":ToggleTerm<cr>", "Split Terminal"}
```

**Comment by tabot-kevin** [comment]
I enabled the plugins and ran PackerUpdate, it seems to be working now, however I am still getting the message that `You need to install treesitter`
<img width="1920" alt="Screen Shot 2021-09-27 at 2 39 02 PM" src="https://user-images.githubusercontent.com/81575086/134919797-60daf7cc-40ea-4a42-8c30-0e8be09cf637.png">

And also when I try to open the file explorer with `space e` I get the error `Not an Editor command:  NvimTreeToggle`
<img width="1920" alt="Screen Shot 2021-09-27 at 2 39 16 PM" src="https://user-images.githubusercontent.com/81575086/134919865-78c99723-775c-4565-af70-30e0e6c91c8a.png">

**Comment by hackorum** [comment]
Run `:PackerSync. Can you share your user-config file? Dashboard does not appear to be working properly for some reason

**Comment by tabot-kevin** [comment]
Hey @hackorum I copied your config and ran :PackerSync, everything seems to be great. Thank you so much.

<img width="1911" alt="Screen Shot 2021-09-27 at 2 57 12 PM" src="https://user-images.githubusercontent.com/81575086/134923009-9b64ee82-0836-4908-b1ed-a533bf947c0d.png">
