### ISSUE TITLE
Neoterm - How to switch windows/tabs?

### ISSUE THREAD

**Issue by KarolusD** [hackorum/VapourNvim#29]
Is it possible to switch to different window or open new tab when neoterm is opened? Leader key seems to be disabled when neoterm is focused, even if terminal supports vi mode. Shortcuts like (Ctrl+K or Ctrl+J) doesn't seem to work too. Mouse works in terms of switching panes, but when I am trying to open new tab from the working tree, neoterm wants to pick a window, after typing any number or letter nothing really happens. Any idea? 

I discover that terminal can be minimalize by hitting `ctr+\` and it doesn't kill the terminal (all process are still running in the background, but it's only a workaround)
![image](https://user-images.githubusercontent.com/35146988/134925668-9da73d67-0f2d-4f4c-a245-0c20d893026e.png)

**Comment by hackorum** [comment]
Add `vim.api.nvim_set_keymap('t', '<esc>', '<C-\\><C-n>', {noremap = true, silent = true})` in your user-config file then if you press escape in the terminal and press ctrl+k. When opening a file from the nvimtree if you press a then it should open a buffer at the top. If you want to close the terminal then you can simply type exit in the terminal. And it's ToggleTerm btw.

**Comment by hackorum** [comment]
#25

**Comment by KarolusD** [comment]
Thanks, it worked.

**Comment by KarolusD** [comment]
The only problem I see with it is that LazyGit terminal do not support `ESC` key now, but I guess you can map different key for that.
