### ISSUE TITLE
 How to enable similar code highlight?

### ISSUE THREAD

**Issue by tabot-kevin** [hackorum/VapourNvim#31]
How do I enable similar code highlight, like the attached image?

<img width="779" alt="Screen Shot 2021-09-28 at 1 55 17 PM" src="https://user-images.githubusercontent.com/81575086/135091061-61f22733-bdbd-4188-b01f-aa209603d8cc.png">

**Comment by hackorum** [comment]
There's a plugin called vim-illuminate to do this. https://github.com/RRethy/vim-illuminate. You can install it by adding this: `Vapour.plugins.user = {{'RRethy/vim-illuminate}}`
