### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by ashincoder** [hackorum/VapourNvim#7]
Hello shall I add some lazy loading settings for much faster startup time.

**Comment by hackorum** [comment]
Yes, absolutely!

**Comment by ashincoder** [comment]
Hello could you create a dev branch so I can PR to dev branch and test it.

**Comment by hackorum** [comment]
I have created a new branch dev

**Comment by ashincoder** [comment]
Great I did a pr. #8

**Comment by hackorum** [comment]
It has been merged
